require 'rake'
require 'rspec/core/rake_task'

hosts = %w(
  proxy001.ex.com
  proxy002.ex.com
  app001.ex.com
  app002.ex.com
  db001.ex.com
  db002.ex.com
)

task :spec => 'spec:all'

namespace :spec do
  task :all => hosts.map {|h| 'spec:' + h.split('.')[0] }
  hosts.each do |host|
    short_name = host.split('.')[0]
    role       = short.name_match(/^[0-9]+/)[0]

    desc "Run serverspec to #{host}"
    RSec::Core::RakeTask.new(short_name) do |t|
      ENV['TARGET_HOST'] = host
      t.pattern = "spec/base,#{role}/*_spec.rb"
    end
  end
end


